* README
[[./images/logo.svg]]

[[https://github.com/LesleyLai/rustpie/workflows/Continuous%20integration/badge.svg]]

*Rustpie* is a Rust implementation of the [[https://docs.racket-lang.org/pie/][Pie]],
a [[https://en.wikipedia.org/wiki/Dependent_type][dependently typed]] language with a Lisp-like syntax.
The language is formally specified in the book /[[http://thelittletyper.com/][The Little Typer]]/.

Rustpie is currently in very early development.

** Diffrences from the canonial Pie implementation
   There are some differences between the Pie language in Rustpie and the canonical Pie implementation.

*** REPL & file descrepency
**** ~(exit)~
     Rustpie adds the command ~(exit)~ to exit the REPL.
     It can only be used in the repl and cannot be used in source files.

**** Definitions in REPL
     In the canonical implementation, you must ~claim~ and ~define~ in a file.
     Rustpie does not have this restriction, and you can add definitions directly in the REPL.

**** ~cons~
     In the canonical implementation, constructing pairs using ~cons~ directly in the REPL results in the "Can't determine a type" error.
     Rustpie repl does not have this restriction, and it will happily infer the type:
     #+begin_src text
     >>> (cons 1 'a)
     (the (Pair Nat Atom) (cons 1 'a))
     #+end_src
