COMMENT = _{ "#|" ~ (!"|#" ~ ANY)* ~ "|#" | ";;" ~ ANY* ~ NEWLINE }
WHITESPACE = _{ (" " | NEWLINE ) }

ident = @{ nondigit ~ (nondigit | ASCII_DIGIT)* }
    nondigit = { LETTER | MATH_SYMBOL | DASH_PUNCTUATION }

atom = @{ "'" ~ ident }

cons = { "(" ~ "cons" ~ expr ~ expr ~ ")" }

pair = { "(" ~ "Pair" ~ expr ~ expr ~ ")" }

sexpr = { "(" ~ expr ~ expr* ~ ")" }

expr = { cons | pair | atom | ident | sexpr }

pie = { SOI ~ expr* ~ EOI }